CREATE SCHEMA IF NOT EXISTS `test`;

CREATE TABLE IF NOT EXISTS `test`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id`));
