version: "1.0"

application:
  name: "Broker"

server:
  port: 8888

db:
  #url: jdbc:mysql
  url: jdbc:postgresql
  host: localhost
  #port: 3309 #Docker mysql
  port: 5432
  #user: root
  user: postgres
  #password: root
  password: secret
  name: vertx-stock-broker
# jdbc:mysql://127.0.0.1:3306/?user=root
